# Date    : 2018/07/26
# Author  : Snow Yang
# Mail    : yangsw@mxchip.com

EXTRA_POST_BUILD_TARGETS += image_xip all_bin ota_bin

TEXT_OUTPUT_FILE           :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.text.bin)
DATA_OUTPUT_FILE           :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.data.bin)

image_xip:
	$(OBJCOPY) -j .xip_image2.text -Obinary $(LINK_OUTPUT_FILE) $(TEXT_OUTPUT_FILE)
	$(OBJCOPY) -j .ram_image2.entry -j .ram_image2.text -j .ram_image2.data -Obinary $(LINK_OUTPUT_FILE) $(DATA_OUTPUT_FILE)
	$(PYTHON) $(SOURCE_ROOT)/platform/mcu/rtl8710bn/pick.py $(TEXT_OUTPUT_FILE) $(DATA_OUTPUT_FILE) $(BIN_OUTPUT_FILE)
	$(RM) $(TEXT_OUTPUT_FILE) $(DATA_OUTPUT_FILE)
	$(RM) $(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.xip2$(LINK_OUTPUT_SUFFIX)) $(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.xip2.stripped$(LINK_OUTPUT_SUFFIX)) $(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.xip2$(BIN_OUTPUT_SUFFIX))

GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT:= $(SCRIPTS_PATH)/gen_common_bin_output_file.py

ALL_BIN_OUTPUT_FILE :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.all$(BIN_OUTPUT_SUFFIX))
OTA_BIN_OUTPUT_FILE :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.ota$(BIN_OUTPUT_SUFFIX))

all_bin: image_xip
	$(QUIET)$(ECHO) Generate $(ALL_BIN_OUTPUT_FILE) ...
	$(QUIET)$(RM) $(ALL_BIN_OUTPUT_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(ALL_BIN_OUTPUT_FILE) -f 0x000000 $(SOURCE_ROOT)board/mk3080/boot.bin
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(ALL_BIN_OUTPUT_FILE) -f 0x013000 $(BIN_OUTPUT_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(ALL_BIN_OUTPUT_FILE) -f 0x0D0000 $(SOURCE_ROOT)board/mk3080/ate.bin

ota_bin: $(BIN_OUTPUT_FILE)
	$(CP) $(BIN_OUTPUT_FILE) $(OTA_BIN_OUTPUT_FILE)
