NAME := board_tg7100cevb

MODULE               := tg7100cevb
HOST_ARCH            := RISC-V
HOST_MCU_FAMILY      := tg7100c
SUPPORT_BINS         := no

$(NAME)_SOURCES := board.c

GLOBAL_INCLUDES += .

GLOBAL_DEFINES += STDIO_UART=0
GLOBAL_DEFINES += RHINO_CONFIG_TICK_TASK=0 RHINO_CONFIG_WORKQUEUE=0
GLOBAL_DEFINES += AOS_CLI_MINI_SIZE=1
GLOBAL_CFLAGS += -DBOARD_TG7100CEVB

CONFIG_SYSINFO_OS_VERSION := $(call get-os-version)
CONFIG_SYSINFO_PRODUCT_MODEL := ALI_AOS_TG7100CEVB
CONFIG_SYSINFO_DEVICE_NAME := TG7100CEVB

GLOBAL_CFLAGS += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\" 
GLOBAL_CFLAGS += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\" 
#GLOBAL_CFLAGS += -DRHINO_CONFIG_NORMAL_PRT=1  -DCONFIG_AOS_CLI_STACK_SIZE=1024  -DAOS_CLI_MINI_SIZE=1
GLOBAL_CFLAGS += -DRHINO_CONFIG_NORMAL_PRT=1

#
# #board config domain
#  #
CONFIG_BOARD_FLASH_SIZE := 2

#firmware config domain
#set CONFIG_ENABLE_ACP to 1 to enable ACP, set to 0 or comment this line to disable
#CONFIG_ENABLE_ACP:=1
CONFIG_BL_IOT_FW_AP:=1
CONFIG_BL_IOT_FW_AMPDU:=0
CONFIG_BL_IOT_FW_AMSDU:=0
CONFIG_BL_IOT_FW_P2P:=0
CONFIG_ENABLE_PSM_RAM:=1
#CONFIG_ENABLE_CAMERA:=1
#CONFIG_ENABLE_BLSYNC:=1
#CONFIG_ENABLE_VFS_SPI:=1
CONFIG_ENABLE_VFS_ROMFS:=1

# set easyflash env psm size, only support 4K、8K、16K options
CONFIG_ENABLE_PSM_EF_SIZE:=16K
CONFIG_FREERTOS_TICKLESS_MODE:=0
#
#    CONFIG_BT:=1
#     CONFIG_BT_STACK_CLI:=1
#      CONFIG_BT_MESH?=1
#       CONFIG_BT_MESH_MODEL_GEN_SRV?=1
#        CONFIG_BLE_TP_SERVER?=1
#
#         #blog enable components format :=blog_testc cli vfs helper

CONFIG_TG7100C_USE_ROM_DRIVER:=1


