NAME := helloworld

$(NAME)_SOURCES := helloworld.c

GLOBAL_DEFINES += AOS_NO_WIFI
GLOBAL_DEFINES += DISABLE_SECURE_STORAGE

$(NAME)_COMPONENTS := yloop cli

ifeq ($(BENCHMARKS),1)
$(NAME)_COMPONENTS  += benchmarks
GLOBAL_DEFINES      += CONFIG_CMD_BENCHMARKS
endif

