OTA_BIN_OUTPUT_FILE := $(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.ota$(BIN_OUTPUT_SUFFIX))

EXTRA_POST_BUILD_TARGETS += $(OTA_BIN_OUTPUT_FILE)

$(OTA_BIN_OUTPUT_FILE):
	$(PYTHON) platform/mcu/asr5502/ota.py $(BIN_OUTPUT_FILE)
	$(PYTHON) platform/mcu/asr5502/add_md5.py $(OTA_BIN_OUTPUT_FILE)